# Do not modify this file!  Generated by nixos-generate-config

{
  # Imports are empty because modulesPath is no longer available in flakes
  imports = [];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/5d571243-0560-4e3a-9416-964613de6727";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/28F9-A557";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = "x86_64-linux";

  # microcode updates
  hardware.cpu.intel.updateMicrocode = true;
}
